#!/usr/bin/env bash
# =============================================================================
# proxmox-config-snapshot.sh
# Generates a markdown snapshot of your Proxmox configuration.
# Intended to be committed to a Git repo as a rebuild reference.
#
# Usage: bash proxmox-config-snapshot.sh
# Must be run as root on the Proxmox node.
# =============================================================================

set -euo pipefail

# --- Configuration -----------------------------------------------------------
OUTPUT_FILE="./proxmox-config-doc_$(date '+%Y-%m-%d').md"
WIZARD_MANIFEST="/mnt/lxc_shares/.wizard-manifest.json"
LXC_CONF_DIR="/etc/pve/lxc"
QEMU_CONF_DIR="/etc/pve/qemu-server"

# --- Helpers -----------------------------------------------------------------

# Print a top-level section header
section() {
    echo "" >> "$OUTPUT_FILE"
    echo "---" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "## $1" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Print a subsection header
subsection() {
    echo "" >> "$OUTPUT_FILE"
    echo "### $1" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Embed a file in a fenced code block; gracefully handle missing files
embed_file() {
    local filepath="$1"
    local lang="${2:-}"
    if [[ -f "$filepath" ]]; then
        echo "\`\`\`${lang}" >> "$OUTPUT_FILE"
        cat "$filepath" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "\`\`\`" >> "$OUTPUT_FILE"
    else
        echo "_File not found: \`$filepath\`_" >> "$OUTPUT_FILE"
    fi
}

# Embed output of a command in a fenced code block
embed_cmd() {
    local label="$1"
    shift
    echo "\`\`\`" >> "$OUTPUT_FILE"
    "$@" 2>/dev/null || echo "(command failed or not available)"
    echo "\`\`\`" >> "$OUTPUT_FILE"
}

# Check that we're running as root
if [[ "$EUID" -ne 0 ]]; then
    echo "Error: This script must be run as root." >&2
    exit 1
fi

# Check for required tools
for cmd in jq pvesh; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "Warning: '$cmd' not found. Some sections may be incomplete." >&2
    fi
done

# =============================================================================
# Start writing the document
# =============================================================================

NODE_NAME=$(hostname)
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
PVE_VERSION=$(pveversion 2>/dev/null || echo "unknown")

cat > "$OUTPUT_FILE" <<EOF
# Proxmox Configuration Reference — ${NODE_NAME}

> **Generated:** ${TIMESTAMP}
> **Node:** ${NODE_NAME}
> **Proxmox Version:** ${PVE_VERSION}
>
> This document is auto-generated by \`proxmox-config-snapshot.sh\`.
> It serves as a human-readable rebuild reference. Do not edit manually.

EOF

# =============================================================================
# 1. FSTAB
# =============================================================================
section "fstab"
echo "_Source: \`/etc/fstab\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
embed_file "/etc/fstab" "text"

# =============================================================================
# 2. NETWORK CONFIGURATION
# =============================================================================
section "Network Configuration"
echo "_Source: \`/etc/network/interfaces\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
embed_file "/etc/network/interfaces" "text"

# =============================================================================
# 3. GRUB
# =============================================================================
section "GRUB Configuration"
echo "_Source: \`/etc/default/grub\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
embed_file "/etc/default/grub" "text"

# =============================================================================
# 4. ZFS
# =============================================================================
section "ZFS"

subsection "Pool Overview"
echo "_Output of \`zpool list\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
{
    echo '```'
    zpool list 2>/dev/null || echo "(zpool not available)"
    echo '```'
} >> "$OUTPUT_FILE"

subsection "Pool Status"
echo "_Output of \`zpool status\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
{
    echo '```'
    zpool status 2>/dev/null || echo "(zpool not available)"
    echo '```'
} >> "$OUTPUT_FILE"

subsection "Dataset List"
echo "_Output of \`zfs list\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
{
    echo '```'
    zfs list 2>/dev/null || echo "(zfs not available)"
    echo '```'
} >> "$OUTPUT_FILE"

subsection "PVE Storage Config"
echo "_Source: \`/etc/pve/storage.cfg\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
embed_file "/etc/pve/storage.cfg" "text"

# =============================================================================
# 5. LXC CONTAINERS
# =============================================================================
section "LXC Containers"

if compgen -G "${LXC_CONF_DIR}/*.conf" > /dev/null 2>&1; then

    # Summary table
    echo "| ID | Hostname | Cores | RAM (MB) | Root Disk | Network |" >> "$OUTPUT_FILE"
    echo "|----|----------|-------|----------|-----------|---------|" >> "$OUTPUT_FILE"

    for conf in "${LXC_CONF_DIR}"/*.conf; do
        ctid=$(basename "$conf" .conf)

        hostname=$(grep -m1 '^hostname:' "$conf" | awk '{print $2}' || echo "—")
        cores=$(grep -m1 '^cores:' "$conf" | awk '{print $2}' || echo "—")
        memory=$(grep -m1 '^memory:' "$conf" | awk '{print $2}' || echo "—")

        # Root disk — grab the size value from rootfs line
        rootfs_line=$(grep -m1 '^rootfs:' "$conf" || echo "")
        rootfs_size=$(echo "$rootfs_line" | grep -oP 'size=\K[^,]+' || echo "—")
        rootfs_vol=$(echo "$rootfs_line" | awk '{print $2}' | cut -d',' -f1 || echo "—")
        root_disk="${rootfs_vol} (${rootfs_size})"

        # Network — collect all net lines
        net_info=$(grep '^net' "$conf" \
            | sed 's/^net[0-9]*: //' \
            | grep -oP '(ip=|ip6=)[^,]+' \
            | tr '\n' ' ' \
            | sed 's/ $//' \
            || echo "—")
        [[ -z "$net_info" ]] && net_info="—"

        echo "| ${ctid} | ${hostname} | ${cores} | ${memory} | ${root_disk} | ${net_info} |" >> "$OUTPUT_FILE"
    done

else
    echo "_No LXC container configs found in \`${LXC_CONF_DIR}\`._" >> "$OUTPUT_FILE"
fi

# =============================================================================
# 6. VIRTUAL MACHINES (QEMU)
# =============================================================================
section "Virtual Machines (QEMU)"

if compgen -G "${QEMU_CONF_DIR}/*.conf" > /dev/null 2>&1; then

    # Summary table
    echo "| ID | Name | Cores | RAM (MB) | Boot Disk | Network |" >> "$OUTPUT_FILE"
    echo "|----|------|-------|----------|-----------|---------|" >> "$OUTPUT_FILE"

    for conf in "${QEMU_CONF_DIR}"/*.conf; do
        vmid=$(basename "$conf" .conf)

        name=$(grep -m1 '^name:' "$conf" | awk '{print $2}' || echo "—")
        cores=$(grep -m1 '^cores:' "$conf" | awk '{print $2}' || echo "—")
        memory=$(grep -m1 '^memory:' "$conf" | awk '{print $2}' || echo "—")

        # Boot disk — find the first scsi/virtio/ide/sata disk
        boot_disk=$(grep -m1 -E '^(scsi|virtio|ide|sata)[0-9]+:' "$conf" \
            | awk '{print $2}' | cut -d',' -f1 \
            || echo "—")

        # Network — collect all net lines, extract model and ip if static
        net_info=$(grep '^net' "$conf" \
            | sed 's/^net[0-9]*: //' \
            | grep -oP '(virtio|e1000|vmxnet3)=[^,]+' \
            | cut -d'=' -f1 \
            | tr '\n' ',' \
            | sed 's/,$//' \
            || echo "—")
        [[ -z "$net_info" ]] && net_info="—"

        echo "| ${vmid} | ${name} | ${cores} | ${memory} | ${boot_disk} | ${net_info} |" >> "$OUTPUT_FILE"
    done

else
    echo "_No VM configs found in \`${QEMU_CONF_DIR}\`._" >> "$OUTPUT_FILE"
fi

# =============================================================================
# 7. CRONTAB
# =============================================================================
section "Crontab (root)"

cron_output=$(crontab -l 2>/dev/null || true)
if [[ -n "$cron_output" ]]; then
    echo '```' >> "$OUTPUT_FILE"
    echo "$cron_output" >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
else
    echo "_No crontab entries found for root._" >> "$OUTPUT_FILE"
fi

# System-wide cron files
if [[ -d /etc/cron.d ]] && [[ -n "$(ls -A /etc/cron.d 2>/dev/null)" ]]; then
    subsection "System Cron (/etc/cron.d)"
    for f in /etc/cron.d/*; do
        [[ -f "$f" ]] || continue
        echo "**\`$(basename "$f")\`**" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo '```' >> "$OUTPUT_FILE"
        cat "$f" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo '```' >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done
fi

# =============================================================================
# 8. WIZARD MANIFEST (.wizard-manifest.json)
# =============================================================================
section "LXC Bind Mount Wizard Manifest"

echo "_Source: \`${WIZARD_MANIFEST}\`_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

if [[ -f "$WIZARD_MANIFEST" ]]; then
    if command -v jq &>/dev/null; then

        wizard_version=$(jq -r '.wizard_version // "unknown"' "$WIZARD_MANIFEST")
        created=$(jq -r '.created // "unknown"' "$WIZARD_MANIFEST")
        op_count=$(jq -r '.operations | length' "$WIZARD_MANIFEST" 2>/dev/null || echo "0")

        echo "> **Wizard Version:** ${wizard_version} | **Created:** ${created} | **Total Mount Operations:** ${op_count}" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        # --- Summary table ---------------------------------------------------
        subsection "Mount Operations Summary"

        echo "| LXC ID | Mount Name | Share Path | Host Mount Point | Container Path | UID:GID (host) | RO | Status |" >> "$OUTPUT_FILE"
        echo "|--------|------------|------------|------------------|----------------|----------------|----|--------|" >> "$OUTPUT_FILE"

        jq -r '.operations[] | [
            .lxc_id,
            .mount_name,
            ("//\(.share_ip)/\(.share_path)"),
            .mount_point,
            .target_path,
            "\(.host_uid):\(.host_gid)",
            (if .read_only then "✓" else "✗" end),
            .status
        ] | @tsv' "$WIZARD_MANIFEST" 2>/dev/null \
        | while IFS=$'\t' read -r lxc_id mount_name share_path host_mp container_path uid_gid ro status; do
            echo "| ${lxc_id} | ${mount_name} | \`${share_path}\` | \`${host_mp}\` | \`${container_path}\` | ${uid_gid} | ${ro} | ${status} |" >> "$OUTPUT_FILE"
        done

        # --- Per-operation rebuild details ------------------------------------
        subsection "Rebuild Details (per mount)"

        echo "_The entries below are the exact lines needed to recreate each mount from scratch._" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        jq -c '.operations[]' "$WIZARD_MANIFEST" 2>/dev/null \
        | while IFS= read -r op; do
            lxc_id=$(echo "$op" | jq -r '.lxc_id')
            mount_name=$(echo "$op" | jq -r '.mount_name')
            share_ip=$(echo "$op" | jq -r '.share_ip')
            share_path=$(echo "$op" | jq -r '.share_path')
            creds_file=$(echo "$op" | jq -r '.creds_file')
            username=$(echo "$op" | jq -r '.username')
            domain=$(echo "$op" | jq -r '.domain // ""')
            host_uid=$(echo "$op" | jq -r '.host_uid')
            host_gid=$(echo "$op" | jq -r '.host_gid')
            container_uid=$(echo "$op" | jq -r '.container_uid')
            container_gid=$(echo "$op" | jq -r '.container_gid')
            read_only=$(echo "$op" | jq -r 'if .read_only then "Yes" else "No" end')
            timestamp=$(echo "$op" | jq -r '.timestamp')
            fstab_entry=$(echo "$op" | jq -r '.fstab_entry')
            lxc_conf_entry=$(echo "$op" | jq -r '.lxc_conf_entry')

            echo "#### LXC ${lxc_id} — \`${mount_name}\`" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "| Field | Value |" >> "$OUTPUT_FILE"
            echo "|-------|-------|" >> "$OUTPUT_FILE"
            echo "| Timestamp | ${timestamp} |" >> "$OUTPUT_FILE"
            echo "| Share | \`//${share_ip}/${share_path}\` |" >> "$OUTPUT_FILE"
            echo "| Credentials file | \`${creds_file}\` |" >> "$OUTPUT_FILE"
            echo "| Username | ${username}${domain:+ @ ${domain}} |" >> "$OUTPUT_FILE"
            echo "| Host UID:GID | ${host_uid}:${host_gid} |" >> "$OUTPUT_FILE"
            echo "| Container UID:GID | ${container_uid}:${container_gid} |" >> "$OUTPUT_FILE"
            echo "| Read-only | ${read_only} |" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "**\`/etc/fstab\` entry:**" >> "$OUTPUT_FILE"
            echo '```' >> "$OUTPUT_FILE"
            echo "${fstab_entry}" >> "$OUTPUT_FILE"
            echo '```' >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "**LXC config entry (\`/etc/pve/lxc/${lxc_id}.conf\`):**" >> "$OUTPUT_FILE"
            echo '```' >> "$OUTPUT_FILE"
            echo "${lxc_conf_entry}" >> "$OUTPUT_FILE"
            echo '```' >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        done

    else
        echo "_\`jq\` not installed — embedding raw JSON instead._" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo '```json' >> "$OUTPUT_FILE"
        cat "$WIZARD_MANIFEST" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo '```' >> "$OUTPUT_FILE"
    fi
else
    echo "_Manifest not found at \`${WIZARD_MANIFEST}\`._" >> "$OUTPUT_FILE"
fi

# =============================================================================
# Done
# =============================================================================

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "_End of document. Generated by \`proxmox-document-config.sh\` on ${NODE_NAME} at ${TIMESTAMP}._" >> "$OUTPUT_FILE"

echo "✓ Documentation written to: ${OUTPUT_FILE}"
